project:
  type: website
  output-dir: docs

website:
  title: "A website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Second page
      - href: third.qmd
        text: Further details
        

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



